// pages/team.tsx
"use client";

import Link from "next/link";
import Image from "next/image";
import {usePathname} from "next/navigation";

const teamMembers = [
    { name: "William Poster", role: "Chairman, Board of Directors, Strydent Autonomous Technologies", image: "/img/william-poster.jpg", text: "William Poster is Chair of the Board of Directors of Strydent Autonomous Technologies, Inc.  Mr. Poster is a seasoned business executive and entrepreneur with an outstanding track record of creating, growing, and harvesting business opportunities. The breadth of his capabilities is evidenced by his creation of successful businesses throughout the world. His accomplishments include being the Founder, Chairman, CEO and sole shareholder of multiple companies spanning five continents and over 50 countries. He is known publicly as the former President of General Dynamics-CSCC, a leading edge international communications and technology company that he founded and sold to General Dynamics Corporation (NYSE: GD). In addition to serving on numerous corporate boards, his less public endeavors include projects related to real estate, defense, education, energy, microfinance, and sports, media, music & entertainment. </br></br> During Mr. Poster's career he has skillfully applied his international expertise on both business and political levels. His extensive knowledge of the international technology, defense and communications marketplace was acquired through direct negotiation and construction of sophisticated military and commercial systems for both business and governments in Europe, Asia, Africa, and the Middle East. He has also been successful, as both a principal and a general partner, in creating and developing large-scale real estate and investment projects in the U.S. and abroad. </br></br> Mr. Poster's educational background includes a business degree and a law degree from The University of Michigan and The George Washington University, respectively. He has been  a member of the District of Columbia Bar Association, The Army Navy Club and numerous other professional, civic and social organizations. Other former noteworthy positions include Founder and Director of SECAF, Founder and Managing Partner of The Eagle Rock Group, as well as staff level positions at The United States Securities & Exchange Commission, The United States Small Business Administration, Mitsui Bank Limited, NY, et. al." },
    { name: "Dean L. Fanelli", role: "Ph.D., Chief Executive Officer and President, Strydent Autonomous Technologies", image: "/img/dean-l-fanelli.jpg", text: "Dean L. Fanelli, Ph.D. is Chief Executive Officer and President of Strydent Autonomous Technologies, Inc.  Dr. Fanelli also is on the Board of Directors.  Dean L. Fanelli has more than 25 years of business leadership experience. An attorney by training with a Ph.D. in organic chemistry, Dean has advised multinational companies on IP issues relating to mergers and acquisitions, including corporate governance and setup, drafting and negotiating asset purchase agreements, licensing agreements, shareholder rights agreements and financing for life sciences companies. </br></br> Dean Fanelli has spent the past 15 years directly involved in starting, investing, and exiting assets in various industries.  In 2012, Dean founded PhosImmune, Inc.  PhosImmune, a phosphoneoantigen cancer vaccine company, was acquired in 2016 by Agenus, Inc.  In 2020, Dean co-founded AexeRNA Therapeutics, a lipid nanoparticle delivery company, which was sold in 2023 to BioNTech. This was very disruptive technology.  BioNTech/Pfizer had administered over 4 billion doses of their mRNA Covid vaccine and generated over $50B in revenue.  BioNTech acquired AexeRNA to replace its existing LNP that was being used in the Covid vaccine with AexeRNA’s LNP as AexeRNA had developed an improved LNP with higher targeted delivery, less side effects, and better immune response.  BioNTech is currently incorporating the AexeRNA LNPs in their preclinical candidates. </br></br> Dean is a board member of Children’s Charity Foundation, a Washington, DC based non-profit aimed at assisting children in the greater Washington, DC area. He also serves as a volunteer baseball coach for the Davidsonville Maryland Athletic Association." },
    { name: "John P. Shire", role: "J.D., Chief Operating Officer, Strydent Autonomous Technologies", image: "/img/john-p.jpg", text: "John Shire focuses has expertise working with both public and private companies in acquisitions, investments, debt financings, joint ventures, commercial contracts, private placements, and impact investments. With a deep understanding of federal and state regulations governing reimbursement, fraud and abuse, compliance and enforcement matters, John is widely regarded for his innovative, hands-on approach.  John’s ability to work seamlessly with his colleagues has solidified his reputation for leading dynamic, cohesive teams that consistently exceed expectations. John serves as outside general counsel to a variety of entities at the leading edge of innovation. He has unique experience representing investment banks and private funds in technology and digital health care transactions.  John co-founded AexeRNA Therapeutics, a lipid nanoparticle delivery company, which was sold in 2023 to BioNTech." },
    { name: "Mike Smith", role: "Board of Advisors Member, Strydent Autonomous Technologies", image: "/img/mike-smith.jpg", text: "Mike Smith is currently CEO of Hanwha Defense USA. Mike is a purpose-driven, tested senior executive and U.S. Navy veteran with over 20 years of experience in the Aerospace and Defense (A&D) industry. His strategic insights and ability to help organizations see around corners have made him a highly sought-after board representative with over a dozen joint venture and LLC directorships across multiple sectors. Which is more, Mike’s vast international experience, rare combination of business acumen, and ability to connect deeply with stakeholders have allowed him to build a track record of dramatically improving profitability and maximizing the potential of executive teams. Mike is known for inspiring organizations to take bold and decisive action resulting in over $14B of new, organic value across his career. Mike co-founded Incrementium Advisors, a consultancy that assists mid-tier A&D companies in their endeavors to expand into new markets, achieve production scale, and unlock margin expansion. He acquired this array of expertise through the repeated successful execution across multiple domains and organizational levels in companies operating worldwide. In 2017, Mike was recognized as one of the Top 300 Black Executives in Corporate America by Black Enterprise Magazine. He is a member of the National Association of Corporate Directors, pursuing Directorship certification." },
    { name: "Frank Gerace", role: "Director of Engineering, Board of Advisors Member, Strydent Autonomous Technologies", image: "/img/Frank-Gerace.jpg", text: "Mr. Frank Gerace served as Division Quality Assurance (QA) Director, Naval Warfare Centers. In this capacity, he provides executive leadership for executing the Navy’s Quality Assurance for all products and services across all ships, submarines, aircraft carriers, unmanned vehicles and assigned systems ensuring Navy craft and systems are safe to operate and mission capable. </br></br> Mr. Gerace began his career serving our nation in 1984 at Naval Surface Warfare Center (NSWC), Philadelphia. Over a 40-year career in Philadelphia, Mr. Gerace developed technical expertise in  propulsion and electrical machinery systems and auxiliary system controls. His expertise includes SUBSAFE design and certification, submarine radar and communication system design and sustainment, full-scale propulsion and electric plant design, construction, and testing of machinery and navigation systems. </br></br> Most recently, Mr. Gerace served as In-Service Submarine Director at NSWC Philadelphia where he led the Navy’s delivery of full-scale machinery testing capabilities for Los Angeles Class Flight III and Seawolf Class Submarine acquisition program, as well as the Division’s efforts advancing research, development, test and evaluation (RDT&E) for undersea vehicle machinery, ship systems, equipment and material. Demonstrating leadership in technical, financial, and business planning, Mr. Gerace developed and formulated Warfare Center Quailty Programs ISO based strategic direction, assisted in improving capability and capacity in facilities, tools and business systems. </br></br> Mr. Gerace earned a Bachelor's Degree in Mechanical Engineering in 1982 and Master of Executive Management Graduate School, USDA in 2003. A Navy Acquisition Corps member, he maintains Level III certification in Systems Engineering." },
    { name: "Admiral Michael Jabaley Ret.", role: "Board of Advisors Member, Strydent Autonomous Technologies", image: "/img/admiral-michael-jabaley-ret.jpg", text: "Michael Jabaley is on the Board of Advisors of Strydent Autonomous Technologies.  Michael previously served as Special Assistant to the Under Secretary of the Navy, supporting the Australia, United Kingdom, United States (AUKUS) trilateral agreement to provide conventionally-armed, nuclear- powered submarines to Australia.  Prior to this he was the Principal for Department of Defense Strategy (USN/USMC) at Amazon Web Services, a position he held from September 2021 to October 2023. He is also the founder and owner of Jabaley Defense Consulting, LLC, and was active as an Independent Consultant from 2018 to 2021. He retired as a Rear Admiral in October 2018 after a 34-year career in Submarines and Navy acquisition. He has extensive operational and procurement experience including at the highest classification levels. Jabaley’s sea tours included assignments aboard USS Drum (SSN 677), USS Ohio (SSBN 726), USS City of Corpus Christi (SSN 705) and command of USS Louisville (SSN 724). Significant shore tours included on the staff of Director, Naval Reactors; on the staff of the Joint Chiefs of Staff; and duty in the Virginia Class Submarine Program Office from 2006 to 2012, the last four years as program manager. Jabaley’s flag assignments included NAVSEA Vice Commander, NAVSEA Deputy Commander for Undersea Warfare, and command of Naval Undersea Warfare Center. Jabaley was selected for his second star in March 2015 and relieved as Program Executive Officer (PEO) Submarines in October 2015, where his portfolio included the Columbia SSBN and Virginia SSN programs, the 2nd and 3rd largest programs in the Department of Defense." },
    { name: "Nickolas Guertin", role: "Board of Advisors Member, Strydent Autonomous Technologies", image: "/img/nickolas-guertin.jpg", text: "Nickolas Guertin is on the Board of Advisors of Strydent Autonomous Technologies.  Prior to this the Honorable Nickolas H. Guertin was sworn in as Director, Operational Test and Evaluation on December 20, 2021. A Presidential appointee confirmed by the United States Senate, he served as the senior advisor to the Secretary of Defense on operational and live fire test and evaluation of Department of Defense weapon systems. </br></br> Mr. Guertin has an extensive four-decade combined military and civilian career in submarine operations, ship construction and maintenance, development and testing of weapons, sensors, combat management products including the improvement of systems engineering, and defense acquisition. He has performed applied research for government and academia in software-reliant and cyber-physical systems at Carnegie Mellon University’s Software Engineering Institute." },
    { name: "Thomas Reynolds", role: "Board of Advisors Member, Strydent Autonomous Technologies", image: "/img/thomas-reynolds.jpg", text: "Tom Reynolds is on the Board of Advisors of Strydent Autonomous Technologies.  Tom has 20+ years’ experience working with unmanned, robotic, and autonomous systems operations, design, development and sustainment.  Tom is a proven leader and has provided strategy and business development leadership with large and small, U.S. and International, commercial and defense robotics businesses capturing over $1B in revenue.  Tom is a retired U.S. Navy Special Operations Officer, Task Group Commander and Commanding Officer. </br></br> Tom is also a board member and executive committee member of Association of Uncrewed Vehicle Systems International (AUVSI) - world large trade association for Unmanned / Robotic Autonomous Systems and a trustee with the U.S. Naval Academy (AS&P)" },
];

export default function TeamPage() {
    const pathname = usePathname();
    const isHome = pathname === "/";

    return (
        <section className="team-one bg-white">
            <div className="container">
                {
                    isHome
                        ?
                        <div className="row mb-4">
                            <div className="col-lg-8 col-md-12 m-auto">
                                <div className="heading-box text-center">
                                    <span className="heading-subtitle border-0">OUR TEAM</span>
                                    <h2 className="heading-title">Meet the Minds Behind the Mission</h2>
                                </div>
                            </div>
                        </div>
                        :
                        ''
                }
                <div className="row gutter-y-30 justify-content-center" id="team-sliderd">
                    {teamMembers.map((member, index) => (
                        <div className="col-lg-3 col-md-6 col-sm-12" key={index}>
                            <div className="team-one-box">
                                <Link
                                    href={{
                                        pathname: "/team-details",
                                        query: {
                                            name: member.name,
                                            role: member.role,
                                            image: member.image,
                                            text: member.text,
                                        },
                                    }}
                                >
                                    <div className="team-one-image">
                                        <Image
                                            src={member.image}
                                            width={306}
                                            height={435}
                                            alt={member.name}
                                        />
                                    </div>
                                    <div className="team-one-details">
                                        <div className="team-one-details-inner">
                                            <h5>{member.name}</h5>
                                            <p>{member.role}</p>
                                        </div>
                                    </div>
                                </Link>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
}